import asyncio
import httpx
import time
from benchmark import SCENARIOS, run_all_tests, print_summary, warm_up
from google.genai import Client
import os

# Load environment variables from env.local
env_path = "/usr/local/google/home/priyambodo/Coding/DO-PRIYAMBODO/do-adk/env.local"
if os.path.exists(env_path):
    with open(env_path) as f:
        for line in f:
            if line.strip() and not line.startswith("#"):
                try:
                    key, value = line.strip().split("=", 1)
                    os.environ[key] = value.strip("\"'")
                except ValueError:
                    pass

# Set Vertex AI specific variables
os.environ["GOOGLE_GENAI_USE_VERTEXAI"] = "TRUE"
if "PROJECT_ID" in os.environ:
    os.environ["GOOGLE_CLOUD_PROJECT"] = os.environ["PROJECT_ID"]
if "GCP_REGION" in os.environ:
    os.environ["GOOGLE_CLOUD_LOCATION"] = os.environ["GCP_REGION"]

async def main():
    async with httpx.AsyncClient() as client:
        await warm_up(client)
        all_runs = []
        
        for i in range(10):
            print(f"\n=== RUN {i+1} OF 10 ===")
            results = await run_all_tests(client)
            print_summary(results)
            all_runs.append(results)
            
        # Calculate Averages
        print("\n=== FINAL AVERAGES (10 Runs) ===")
        avg_results = {}
        
        for scenario in SCENARIOS:
            native_vals = [r[scenario]["native"] for r in all_runs if r[scenario]["native"] is not None]
            adk_vals = [r[scenario]["adk"] for r in all_runs if r[scenario]["adk"] is not None]
            
            avg_results[scenario] = {
                "native": int(sum(native_vals) / len(native_vals)) if native_vals else None,
                "adk": int(sum(adk_vals) / len(adk_vals)) if adk_vals else None
            }
            
        # Streaming Averages
        n_ttft_vals = [r["stream"]["native"]["ttft"] for r in all_runs if r["stream"]["native"]]
        a_ttft_vals = [r["stream"]["adk"]["ttft"] for r in all_runs if r["stream"]["adk"]]
        n_total_vals = [r["stream"]["native"]["total"] for r in all_runs if r["stream"]["native"]]
        a_total_vals = [r["stream"]["adk"]["total"] for r in all_runs if r["stream"]["adk"]]
        
        avg_results["stream"] = {
            "native": {
                "ttft": int(sum(n_ttft_vals) / len(n_ttft_vals)),
                "total": int(sum(n_total_vals) / len(n_total_vals))
            } if n_ttft_vals else None,
            "adk": {
                "ttft": int(sum(a_ttft_vals) / len(a_ttft_vals)),
                "total": int(sum(a_total_vals) / len(a_total_vals))
            } if a_ttft_vals else None
        }
        
        print_summary(avg_results)
        
        # Real-time Analysis using Gemini
        print("\n=== COMPREHENSIVE ANALYSIS OF AVERAGES (Generated by Gemini) ===")
        
        try:
            client_ai = Client() # Will pick up GOOGLE_API_KEY from environment
            
            # Convert results to string for prompt
            results_str = ""
            for scenario, data in avg_results.items():
                results_str += f"- {scenario}: Native={data['native']}, ADK={data['adk']}\n"
                
            prompt = f"""
            You are a performance analyst expert. Here are the averaged results of a benchmark run 10 times comparing Google Gen AI Native SDK vs ADK Framework:
            
            {results_str}
            
            Analyze these averaged results. Explain why ADK might be winning or losing in specific scenarios based on these numbers. 
            Address the consistency and variance that might be implied by averages.
            Keep the analysis concise, technical, and actionable. Be direct.
            """
            
            response = client_ai.models.generate_content(
                model="gemini-2.5-flash",
                contents=prompt
            )
            
            print(response.text)
            
        except Exception as e:
            print(f"Failed to generate real-time analysis: {e}")

if __name__ == "__main__":
    asyncio.run(main())
